### Register un nouvel utilisateur

POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "datopin134@amcret.com",
  "password": "monpassword"
}
###

POST http://localhost:3000/users/verify-email
Content-Type: application/json

{
  "email": "datopin134@amcret.com",
  "otp": "723797"
}

### Login pour récupérer le token JWT
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "datopin134@amcret.com",
  "password": "monpassword"
}

###
POST http://localhost:3000/users/logout



### Accéder au profil protégé (remplacer TOKEN par celui reçu au login)
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJkYXRvcGluMTM0QGFtY3JldC5jb20iLCJpYXQiOjE3NTU5MjA5OTMsImV4cCI6MTc1NTkyMTg5M30.Zs-OeKjClKtXJwAXhe1sGHj-oSNEyqXGmBuEqEaOtr8
  